Repository AI4quantum/maestro-knowledge, pull requests merged in 2025-09, with the labels that each got.

#55 chore: PEP585 : use built in generics/modernize typing annotations
  examples/mcp_example.py
  examples/milvus_example.py
  examples/weaviate_example.py
  pyproject.toml
  src/chunking/common.py
  src/chunking/fixed.py
  src/chunking/none.py
  src/chunking/semantic_chunking.py
  src/chunking/sentence.py
  src/db/vector_db_base.py
  src/db/vector_db_milvus.py
  src/db/vector_db_weaviate.py
  src/maestro_mcp/server.py
  tests/chunking/test_common.py
  tests/chunking/test_fixed.py
  tests/chunking/test_none.py
  tests/chunking/test_semantic_chunking.py
  tests/chunking/test_sentence.py
  tests/test_chunking.py
  tests/test_integration_examples.py
  tests/test_mcp_query.py
  tests/test_mcp_server.py
  tests/test_query_functionality.py
  tests/test_query_integration.py
  tests/test_resync.py
  tests/test_vector_database_yamls.py
  tests/test_vector_db_base.py
  tests/test_vector_db_factory.py
  tests/test_vector_db_milvus.py
  tests/test_vector_db_weaviate.py
  tools/bump_version.py
  uv.lock
Labels: chore

#56 bug: fix issue with some write calls not returning response when error occurs
  src/db/vector_db_milvus.py
  src/db/vector_db_weaviate.py
  tests/test_vector_db_milvus.py
  tests/test_vector_db_weaviate.py
Labels: bug

#62 feature: support custom headers for LLM call when using custom embedding
  README.md
  src/db/vector_db_milvus.py
  src/maestro_mcp/README.md
  start.sh
  tests/test_vector_db_milvus.py
Labels: feature

#53 feat: change vector db call to async
  pyproject.toml
  src/db/vector_db_base.py
  src/db/vector_db_milvus.py
  src/db/vector_db_weaviate.py
  src/maestro_mcp/server.py
  tests/test_mcp_query.py
  tests/test_mcp_server.py
  tests/test_query_integration.py
  tests/test_resync.py
  tests/test_vector_db_base.py
  tests/test_vector_db_milvus.py
  tests/test_vector_db_weaviate.py
  uv.lock
Labels: feature

#68 chore: reduce size of docker image
  .dockerignore
  Dockerfile
Labels: chore

#69 chore: add pre-commit-config
  .pre-commit-config.yaml
  pyproject.toml
  uv.lock
Labels: chore
