Repository AI4quantum/maestro-knowledge, pull requests merged in 2025-08, with the labels that each got.

#15 chore: improve resilience of stop.sh
  stop.sh
Labels: chore

#19 feat: Dockerfile for running the mcp server
  .gitignore
  Dockerfile
  start.sh
Labels: enhancement, feature

#24 fix: milvus query missing collection_name arg
  src/db/vector_db_base.py
  src/db/vector_db_milvus.py
Labels: bug

#25 chore: refactor Dockerfile for kubernetes cluster
  Dockerfile
Labels: chore

#31 bug: fix release CI issue with Windows exec
  .github/workflows/cli_release.yml
Labels: bug

#38 chore: update database connection
  README.md
Labels: chore
